Repository oonisidesu/cub3D, pull requests merged in 2025-01, with the labels that each got.

#93 :bug: マップ中に改行、スペースが含まれる場合のエラー処理
  include/utils.h
  map/error/MAP_INVALID_NEWLINE.cub
  map/error/MAP_INVALID_SPACE_LINE.cub
  map/error/ORDER_INVALID_TEXTURE_NAME.cub
  src/parse/parse_cub_file.c
  src/parse/parse_cub_file_process.c
  src/util/util.c
Labels: bug, Task

#96 :art: エラーの場合に一瞬windowが表示される問題を解決
  include/init.h
  src/init/init_data.c
  src/init/init_mlx.c
  src/main.c
Labels: Task

#98 壁がなくなってしまう問題
  src/game/game_move.c
Labels: bug

#97 :bug: ,のバグ修正
  map/error/ORDER_INVALID_COLORCODE_COMMA1.cub
  map/error/ORDER_INVALID_COLORCODE_COMMA2.cub
  map/error/ORDER_INVALID_COLORCODE_COMMA3.cub
  map/error/ORDER_INVALID_COLORCODE_COMMA4.cub
  src/parse/parse_color_line.c
Labels: bug
